In [5]:
import pandas as pd
# Fixing the data to ensure all arrays are of equal length by checking for missing values
data = {
    "DATE": pd.date_range(start="2022-12-06", periods=28),
    "SCORE": [86, 91, 85, 88, None, 89, 76, 84, 88, 85, 84, 87, 71, 89, 83, 84, 86, 0, None, 77, 80, 86, 74, 84, 79, None, 82, 87],
    "PERSONAL SCORE": [78, 92, 90, 85, 55, 85, 85, 87, 88, 90, 84, 88, 80, 85, 85, 88, 82, 0, 70, 83, 83, 85, 87, 85, 82, 70, 82, 90],
    "LAST EATING TIME": ["22:30", "21:30", "00:30", "00:00", "04:30", "22:30", "21:00", "00:00", "23:00", "01:00", "01:00", "22:00", 
                         "22:30", "21:30", "01:00", "00:30", "00:00", "21:00", "02:00", "20:00", "23:00", "01:00", "22:30", "01:30", 
                         "00:00", "03:00", "23:00", "20:00"],
    "PHYSICAL ACTIVITY": ["LIGHT", "INTENSE", "MODERATE", "INTENSE", "LIGHT", "MODERATE", "MODERATE", "LIGHT", "INTENSE", "INTENSE", 
                          "INSTENSE", "INTENSE", "MODERATE", "MODERATE", "LIGHT", "INTENSE", "LIGHT", "NO", "NO", "NO", "INTENSE", 
                          "MODERATE", "MODERATE", "INTENSE", "NO", "INTENSE", "NO", "INTENSE"],
    "LAST CAFFEINE": ["18:30", "16:00", "17:00", "15:30", "21:00", "16:00", "14:00", "16:00", "16:00", "14:00", "22:00", "16:00", 
                      "17:00", "14:00", "23:30", "00:30", "16:00", "16:00", "17:00", "16:00", "15:00", "15:00", "16:00", "16:00", 
                      "16:00", "19:00", "12:00", "16:00"],
    "WEED": ["YES", "NO", "YES", "YES", "NO", "YES", "NO", "NO", "NO", "YES", "YES", "YES", "NO", "NO", "YES", "YES", "YES", "NO", 
             "YES", "NO", "YES", "YES", "NO", "YES", "NO", "YES", "NO", "NO"],
    "ALCOHOL": ["NO", "NO", "NO", "NO", "YES", "NO", "NO", "NO", "NO", "NO", "NO", "NO", "NO", "NO", "NO", "NO", "NO", "NO", "YES", 
                "NO", "NO", "NO", "NO", "NO", "NO", "YES", "NO", "NO"],
    "ACTIVITY BEFORE SLEEPING": ["SEX", "READING", "VIDEOS", "VIDEOS", "MUSIC", "VIDEO", "SEX", "READING", "VIDEOS", "VIDEOS", 
                                 "SEX", "VIDEOS", "SEX", "READING", "VIDEOS", "SEX", "VIDEOS", "TRAVEL", "VIDEOS", "VIDEOS", 
                                 "VIDEOS", "VIDEOS", "VIDEOS", "VIDEOS", "VIDEOS", "PORN", "VIDEOS", "READING"],
    "SLEEP TIME": ["01:30", "23:30", "02:00", "01:00", "05:00", "00:00", "01:00", "01:00", "23:40", "02:07", "02:52", "00:43", 
                   "02:51", "23:56", "02:17", "02:21", "01:52", "02:00", "03:00", "00:24", "02:16", "04:36", "01:24", "02:50", 
                   "02:06", "05:20", "01:40", "01:05"],
    "SLEEP HOURS": [7.35, 9.0, 8.34, 8.24, 6.25, 9.0, 9.47, 8.0, 9.83, 8.78, 7.93, 9.18, 8.45, 9.0, 8.5, 9.22, 8.43, 2.0, 7.5, 
                    10.52, 8.5, 7.47, 9.5, 8.5, 7.87, 7.0, 9.33, 8.58],
    "DEEP SLEEP": [1.29, 2.08, 1.75, 1.95, None, 2.05, 2.03, 1.1, 2.18, 1.65, 2.0, 1.93, 2.01, 2.08, 1.42, 2.27, 1.72, 0, None, 
                   1.93, 1.5, 1.8, 2.07, 1.82, 1.1, None, 1.5, 1.5]
}

df = pd.DataFrame(data)

# Convert time columns into numeric values
df["LAST EATING TIME"] = pd.to_datetime(df["LAST EATING TIME"], format="%H:%M", errors='coerce').dt.hour + pd.to_datetime(df["LAST EATING TIME"], format="%H:%M", errors='coerce').dt.minute/60
df["LAST CAFFEINE"] = pd.to_datetime(df["LAST CAFFEINE"], format="%H:%M", errors='coerce').dt.hour + pd.to_datetime(df["LAST CAFFEINE"], format="%H:%M", errors='coerce').dt.minute/60
df["SLEEP TIME"] = pd.to_datetime(df["SLEEP TIME"], format="%H:%M", errors='coerce').dt.hour + pd.to_datetime(df["SLEEP TIME"], format="%H:%M", errors='coerce').dt.minute/60

# Map categorical and binary data
activity_mapping = {"NO": 0, "LIGHT": 1, "MODERATE": 2, "INTENSE": 3, "INSTENSE": 3}
df["PHYSICAL ACTIVITY"] = df["PHYSICAL ACTIVITY"].map(activity_mapping)
binary_mapping = {"YES": 1, "NO": 0}
df["WEED"] = df["WEED"].map(binary_mapping)
df["ALCOHOL"] = df["ALCOHOL"].map(binary_mapping)

df

,DATE,SCORE,PERSONAL SCORE,LAST EATING TIME,PHYSICAL ACTIVITY,LAST CAFFEINE,WEED,ALCOHOL,ACTIVITY BEFORE SLEEPING,SLEEP TIME,SLEEP HOURS,DEEP SLEEP
0,2022-12-06,86.0,78,22.5,1,18.5,1,0,SEX,1.500000,7.35,1.29
1,2022-12-07,91.0,92,21.5,3,16.0,0,0,READING,23.500000,9.00,2.08
2,2022-12-08,85.0,90,0.5,2,17.0,1,0,VIDEOS,2.000000,8.34,1.75
3,2022-12-09,88.0,85,0.0,3,15.5,1,0,VIDEOS,1.000000,8.24,1.95
4,2022-12-10,NaN,55,4.5,1,21.0,0,1,MUSIC,5.000000,6.25,NaN
5,2022-12-11,89.0,85,22.5,2,16.0,1,0,VIDEO,0.000000,9.00,2.05
6,2022-12-12,76.0,85,21.0,2,14.0,0,0,SEX,1.000000,9.47,2.03
7,2022-12-13,84.0,87,0.0,1,16.0,0,0,READING,1.000000,8.00,1.10
8,2022-12-14,88.0,88,23.0,3,16.0,0,0,VIDEOS,23.666667,9.83,2.18
9,2022-12-15,85.0,90,1.0,3,14.0,1,0,VIDEOS,2.116667,8.78,1.65
10,2022-12-16,84.0,84,1.0,3,22.0,1,0,SEX,2.866667,7.93,2.00
11,2022-12-17,87.0,88,22.0,3,16.0,1,0,VIDEOS,0.716667,9.18,1.93
12,2022-12-18,71.0,80,22.5,2,17.0,0,0,SEX,2.850000,8.45,2.01
13,2022-12-19,89.0,85,21.5,2,14.0,0,0,READING,23.933333,9.00,2.08
14,2022-12-20,83.0,85,1.0,1,23.5,1,0,VIDEOS,2.283333,8.50,1.42
15,2022-12-21,84.0,88,0.5,3,0.5,1,0,SEX,2.350000,9.22,2.27
16,2022-12-22,86.0,82,0.0,1,16.0,1,0,VIDEOS,1.866667,8.43,1.72
17,2022-12-23,0.0,0,21.0,0,16.0,0,0,TRAVEL,2.000000,2.00,0.00
18,2022-12-24,NaN,70,2.0,0,17.0,1,1,VIDEOS,3.000000,7.50,NaN
19,2022-12-25,77.0,83,20.0,0,16.0,0,0,VIDEOS,0.400000,10.52,1.93
20,2022-12-26,80.0,83,23.0,3,15.0,1,0,VIDEOS,2.266667,8.50,1.50
21,2022-12-27,86.0,85,1.0,2,15.0,1,0,VIDEOS,4.600000,7.47,1.80
22,2022-12-28,74.0,87,22.5,2,16.0,0,0,VIDEOS,1.400000,9.50,2.07
23,2022-12-29,84.0,85,1.5,3,16.0,1,0,VIDEOS,2.833333,8.50,1.82
24,2022-12-30,79.0,82,0.0,0,16.0,0,0,VIDEOS,2.100000,7.87,1.10
25,2022-12-31,NaN,70,3.0,3,19.0,1,1,PORN,5.333333,7.00,NaN
26,2023-01-01,82.0,82,23.0,0,12.0,0,0,VIDEOS,1.666667,9.33,1.50
27,2023-01-02,87.0,90,20.0,3,16.0,0,0,READING,1.083333,8.58,1.50

In [4]:



# Calculate correlations
correlations = df.corr()["SCORE"].sort_values(ascending=False)

correlations

ValueError: could not convert string to float: 'SEX'